### ISSUE TITLE
Steps to install/start use

### ISSUE THREAD

**Issue by CristianSitov** [hobo-go/echo-web#1]
Hello! I've managed to setup most of the package, but when I run build.sh I get the following message:

`
/home/vagrant/go/src/github.com/hobo-go/echo-web/echo/echo.go:13:2: no buildable Go source files in /home/vagrant/go/src/github.com/hobo-go/echo-web/assets
/home/vagrant/go/src/github.com/hobo-go/echo-web/modules/render/render.go:19:2: no buildable Go source files in /home/vagrant/go/src/github.com/hobo-go/echo-web/templates
`

**Comment by hobo-c** [comment]
You have install go-bindata?
https://github.com/jteeuwen/go-bindata
