### ISSUE TITLE
command-line-arguments

### ISSUE THREAD

**Issue by wenhao-fly** [hobo-go/echo-web#2]
usr/local/Cellar/go/1.7.4_2/libexec/pkg/tool/darwin_amd64/link: cannot open file /usr/local/Cellar/go/1.7.4_2/libexec/pkg/darwin_amd64/github.com/labstack/echo.a: open /usr/local/Cellar/go/1.7.4_2/libexec/pkg/darwin_amd64/github.com/labstack/echo.a: no such file or directory

?

**Comment by hobo-c** [comment]
有没有
`glide install`

**Comment by wenhao-fly** [comment]
echo/echo.go:113: cannot use www.LoginHandler (type func(*www.Context) error) as type echo.HandlerFunc in argument to e.GET
echo/echo.go:114: cannot use www.RegisterHandler (type func(*www.Context) error) as type echo.HandlerFunc in argument to e.GET
echo/echo.go:115: cannot use www.LogoutHandler (type func(*www.Context) error) as type echo.HandlerFunc in argument to e.GET
echo/echo.go:116: cannot use www.LoginPostHandler (type func(*www.Context) error) as type echo.HandlerFunc in argument to e.POST
echo/echo.go:117: cannot use www.RegisterPostHandler (type func(*www.Context) error) as type echo.HandlerFunc in argument to e.POST

**Comment by hobo-c** [comment]
有自定义了Context，只做了子域名模式echo.RunSubdomains()的支持
echo.Run()注释掉了，没有更新

```
看下这两个
www/context.go
www/router.go
/**
 * 自定义Context的Handler
 */
func handler(h HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		ctx := c.(*Context)
		return h(ctx)
	}
}
```

**Comment by wenhao-fly** [comment]
最近在学习echo写web  能否把run给跑通，万分感谢

**Comment by hobo-c** [comment]
还是跑不通吗？要不感兴趣加QQ或者微信聊
