### ISSUE TITLE
no buildable Go source files

### ISSUE THREAD

**Issue by helpself2005** [hobo-go/echo-web#3]
你好，当我go run server.go 的时候出现no buildable Go source files
[ `go run server.go` | done: 1.976113s ]
  router\www\router.go:11:2: no buildable Go source files in D:\workspace\go\src\echo-web\assets
  module\render\render.go:20:2: no buildable Go source files in D:\workspace\go\src\echo-web\template

**Comment by helpself2005** [comment]
谢谢楼主的分享，我下载了go-bindata，目前可以编译通过了，只是我没有部署redis目前还没有完全调通

**Comment by hobo-c** [comment]
如果想尽快调通可以把cache和session的配置改下不用redis
./conf/conf.go
// Session，可以使用FILE
SESSION_STORE = REDIS // REDIS,FILE,COOKIE(COOKIE Default)
// Cache，可以使用IN_MEMORY
CACHE_STORE = REDIS //REDIS,MEMCACHED,IN_MEMORY(IN_MEMORY Default)

**Comment by hobo-c** [comment]
已更新文档，对非必须的配置简化，快速跑起来😀

**Comment by helpself2005** [comment]
🙏，我今天部署了redis 已经跑起来了，非常感谢；我是想做一个 saas的软件平台；想用go做后端api服务；机会加微信聊 helpself2011
